### PR TITLE
Remove user prefix path

### LINKED ISSUE #68: ResourceLoader uses wrong 'user-skins' path for resources from 'canasta-skins' directory
Most likely we can face similar issues for extensions from canasta-extensions directory.
I don't think we can easily fix it in mw core, the issue is related Canasta design.
cfLoadSkin() function changes $wgStyleDirectory and $wgStylePath variables, calls wfLoadSkin() function and restores values of the variables.  It allows to load skins from canasta-skins directory, but when ResourceLoader compiles (for example) less files, it seems it uses original values of the variables.

For example `.background-image-svg( 'images/external-link-ltr-icon.svg' );` line in `w/canasta-skins/Vector/resources/skins.vector.styles/common/typography.less` file tries to load file from `user-skins /...` directory.

We can bypass this adding a rewrite rule to Apache to look for a file in canasta-skins directory if it does not exist in user-skins directory. This approach is not very good, but should work

P.S.
`cfLoadExtension( 'Bootstrap' );` throws the error:
```
[ec247b7af6bd517a8195dde0] /wiki/Main_Page RuntimeException from line 142 of /var/www/mediawiki/w/canasta-extensions/Bootstrap/src/Hooks/SetupAfterCache.php: Expected an accessible /var/www/mediawiki/w/user-extensions/Bootstrap/resources/bootstrap path

Backtrace:

#0 /var/www/mediawiki/w/canasta-extensions/Bootstrap/src/Hooks/SetupAfterCache.php(73): Bootstrap\Hooks\SetupAfterCache->isReadablePath()
#1 /var/www/mediawiki/w/canasta-extensions/Bootstrap/src/Bootstrap.php(62): Bootstrap\Hooks\SetupAfterCache->process()
#2 /var/www/mediawiki/w/includes/HookContainer/HookContainer.php(329): Bootstrap\Bootstrap::Bootstrap\{closure}()
#3 /var/www/mediawiki/w/includes/HookContainer/HookContainer.php(132): MediaWiki\HookContainer\HookContainer->callLegacyHook()
#4 /var/www/mediawiki/w/includes/HookContainer/HookRunner.php(3417): MediaWiki\HookContainer\HookContainer->run()
#5 /var/www/mediawiki/w/includes/Setup.php(694): MediaWiki\HookContainer\HookRunner->onSetupAfterCache()
#6 /var/www/mediawiki/w/includes/WebStart.php(89): require_once(string)
#7 /var/www/mediawiki/w/index.php(44): require(string)
#8 {main}
```

### PR DESCRIPTION
**Pull request by jeffw16**
Follow ups the https://github.com/CanastaWiki/Canasta/commit/162da7fb628cbe1d3395806556ee024948303367 revert of #60

* Removes processing of custom composer.local.json
* Removes runtimme composer updates
* Modified the check of mounted directories to prevent running with old scheme of `user-` prefixed mounts

Closes #68

### CODE REVIEW

File: _sources/scripts/run-apache.sh [hunk 1]
```diff
@@ -131,86 +131,29 @@ run_autoupdate () {
...
   fi
 
-  # Check for $MW_HOME/extensions presence and bow out if it's in place
-  if [ -d "$MW_HOME/skins" ]; then
-    # Do no composer updates if the directory is in place because this means that
-    # the directory is probably mounted from host and the mount point was not updated to user-extensions
-    echo "WARNING! $MW_HOME/skins is an incorrect mount point, please re-mount to $MW_HOME/user-skins"
+  # Check for $MW_HOME/user-skins presence and bow out if it's in place
+  if [ -d "$MW_HOME/user-skins" ]; then
+    echo "WARNING! As of Canasta 1.0.1, $MW_HOME/user-skins is an incorrect mount point! Please update your Docker Compose stack to 1.0.1 and re-mount to $MW_HOME/skins."
```
Comment (jeffw16) [inline _sources/scripts/run-apache.sh:143]: Should be Canasta 1.1.0

File: _sources/scripts/run-apache.sh [hunk 2]
```diff
@@ -131,86 +131,29 @@ run_autoupdate () {
...
-
 check_mount_points () {
-  # Check for $MW_HOME/extensions presence and bow out if it's in place
-  if [ -d "$MW_HOME/extensions" ]; then
-    # Do no composer updates if the directory is in place because this means that
-    # the directory is probably mounted from host and the mount point was not updated to user-extensions
-    echo "WARNING! $MW_HOME/extensions is an incorrect mount point, please re-mount to $MW_HOME/user-extensions"
+  # Check for $MW_HOME/user-extensions presence and bow out if it's in place
+  if [ -d "$MW_HOME/user-extensions" ]; then
+    echo "WARNING! As of Canasta 1.0.1, $MW_HOME/user-extensions is an incorrect mount point! Please update your Docker Compose stack to 1.0.1 and re-mount to $MW_HOME/extensions."
```
Comment (jeffw16) [inline _sources/scripts/run-apache.sh:137]: Should be Canasta 1.1.0

**Review by pastakhov — APPROVED** [review]
LGTM, I didn't test the built image

**Review by vedmaka — APPROVED** [review]
